# -*- coding: utf-8 -*-
"""Crop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1po2qjjl_rQiQB4h8JWI-NIPPsk7HO_xY
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pickle

data = pd.read_csv("Crop_recommendation.csv")

data.head()

data.shape

data.isnull().sum()

x= data.iloc[:,:-1]
y= data.iloc[:,-1]

print(x)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2,random_state = 42)

x_train.head()

model = RandomForestClassifier()

model.fit(x_train,y_train)

prediction = model.predict(x_test)

accuracy = model.score(x_test,y_test)

print("Accuracy:", accuracy)

new_features =[[36,58,25,28.66024,59.31891,8.399136,36.9263]]
predicted_crop = model.predict(new_features)
print("Predicted Crop:" ,predicted_crop)